# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: status # NOTE: update this with your service name

plugins:
  - serverless-offline

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

custom: ${file(../.serverless.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ENVIRONMENT: ${opt:stage}
    REDIS_HOST: ${env:REDIS_HOST, self:custom.${opt:stage}.REDIS_HOST}

# you can overwrite defaults here
stage: dev
region: us-east-1

# package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  status:
    handler: handler.status
    vpc:
      securityGroupids: ${self:custom:securityGroupids}
      subnetIds: ${self:custom:subnetIds}
    events:
      - http:
          path: status
          method: get
