service: status

plugins:
  - serverless-offline

custom: ${file(../.serverless.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    ENVIRONMENT: ${opt:stage}
    REDIS_HOST: ${env:REDIS_HOST, self:custom.${opt:stage}.REDIS_HOST}

stage: dev
region: us-east-1

functions:
  status:
    handler: handler.status
    vpc:
      securityGroupids: ${self:custom:securityGroupids}
      subnetIds: ${self:custom:subnetIds}
    events:
      - http:
          path: status
          method: get
