service: status

plugins:
  - serverless-offline
  - serverless-plugin-warmup

custom: ${file(../.serverless.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource:
      - Fn::Join:
        - ':'
        - - arn:aws:lambda
          - Ref: AWS::Region
          - Ref: AWS::AccountId
          - function:${self:service}-${opt:stage, self:provider.stage}-*
  vpc:
    securityGroupids: ${self:custom:securityGroupids}
    subnetIds: ${self:custom:subnetIds}
  environment:
    ENVIRONMENT: ${opt:stage}
    REDIS_HOST: ${env:REDIS_HOST, self:custom.${opt:stage}.REDIS_HOST}

stage: dev
region: us-east-1

functions:
  status:
    warmup:
      - production
    handler: handler.status
    memory: 128
    events:
      - http:
          path: status
          method: get
